spring.application.name=notifyService

# Server Port
server.port=8082

# Mail Configuration (using Gmail SMTP as standard placeholder)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhawanomkar80@gmail.com
spring.mail.password=foln xwvp hhoq kxeh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# SMS Service Configuration (Mock Settings for testing / extension)
sms.provider=mock
sms.api.key=key
sms.sender.id=QRDINE
